services:
  agent:
    env_file: [.env]
    command: sh -c 'chmod +x bin/wait; bin/wait && python -m deeppavlov_agent.run -ch http_client --cors'
    build:
      context: ./
      dockerfile: dockerfile_agent
    ports:
      - 4242:4242
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  mongo:
    command: mongod
    image: mongo:4.0.0
version: '3.7'
